language: scala
scala:
  - "2.9"
  - "2.10"
  - "2.11"
  - "2.12"
  - "2"
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
#os:
  #- linux
  #- osx

addons:
  apt:
    packages:
      - tesseract-ocr
env:
  - TESSDATA_PREFIX=/usr/share/tesseract-ocr
