language: scala
scala:
  - "2.9"
  - "2.10"
  - "2.11"
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - tesseract-ocr
env:
  - TESSDATA_PREFIX=/usr/share/tesseract-ocr
