scalaVersion := "2.12.3"
name := "cormorant"
version := "0.0"
libraryDependencies += "net.sourceforge.tess4j" % "tess4j" % "3.4.2"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.4" % "test"
